// Generates src/styles/_tokens.scss from src/theme/tokens.ts: `npm run tokens:build`.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import {
  MF_BREAKPOINT_MD,
  MF_FONT,
  MF_INK,
  MF_LAYOUT,
  MF_LEADING,
  MF_MOTION,
  MF_OVERLAY,
  MF_PASTELS,
  MF_RADIUS,
  MF_SEA,
  MF_SEMANTIC,
  MF_SHADOW,
  MF_SPACE,
  MF_TEXT,
  MF_TONES,
  MF_TRACKING,
  MF_WEIGHT,
  MF_WHITE,
  MF_Z
} from '../src/theme/tokens.ts';

export const TOKENS_SCSS = new URL('../src/styles/_tokens.scss', import.meta.url);

const rem = (px) => `${px / 16}rem`;
const block = (selector, lines) => [`${selector} {`, ...lines.map((line) => '  ' + line), '}'];

export function render() {
  const root = ['// Primitives: only _tokens.scss, MfAvatar and components/viz may reference them.', `--mf-white: ${MF_WHITE};`];
  for (const [step, hex] of Object.entries(MF_SEA)) root.push(`--mf-sea-${step}: ${hex};`);
  for (const [step, hex] of Object.entries(MF_INK)) root.push(`--mf-ink-${step}: ${hex};`);
  MF_PASTELS.forEach((pastel, index) => {
    for (const part of ['bg', 'mid', 'fg']) root.push(`--mf-pastel-${index}-${part}: ${pastel[part]}; // ${pastel.name}`);
  });

  root.push('', '// Semantic colors.');
  for (const [name, primitive] of Object.entries(MF_SEMANTIC)) root.push(`--mf-color-${name}: var(--mf-${primitive});`);
  root.push(`--mf-color-overlay: ${MF_OVERLAY};`);
  for (const [tone, parts] of Object.entries(MF_TONES)) {
    for (const [part, hex] of Object.entries(parts)) root.push(`--mf-tone-${tone}-${part}: ${hex};`);
  }
  MF_PASTELS.forEach((_, index) => {
    root.push(`--mf-chart-${index}: var(--mf-pastel-${index}-mid);`, `--mf-chart-${index}-strong: var(--mf-pastel-${index}-fg);`);
    root.push(`--mf-avatar-${index}-bg: var(--mf-pastel-${index}-bg);`, `--mf-avatar-${index}-fg: var(--mf-pastel-${index}-fg);`);
  });

  root.push('', '// Shape and depth.');
  for (const [name, px] of Object.entries(MF_RADIUS)) root.push(`--mf-radius-${name}: ${px}px;`);
  for (const [name, value] of Object.entries(MF_SHADOW)) root.push(`--mf-shadow-${name}: ${value};`);

  root.push('', '// Typography.');
  for (const [name, value] of Object.entries(MF_FONT)) root.push(`--mf-font-${name}: ${value};`);
  for (const [name, px] of Object.entries(MF_TEXT)) root.push(`--mf-text-${name}: ${rem(px)};`);
  for (const [name, value] of Object.entries(MF_LEADING)) root.push(`--mf-leading-${name}: ${value};`);
  for (const [name, value] of Object.entries(MF_TRACKING)) root.push(`--mf-tracking-${name}: ${value};`);
  for (const [name, value] of Object.entries(MF_WEIGHT)) root.push(`--mf-weight-${name}: ${value};`);

  root.push('', '// Space and layout.');
  for (const [step, px] of Object.entries(MF_SPACE)) root.push(`--mf-space-${step}: ${px}px;`);
  const responsive = [];
  for (const [name, value] of Object.entries(MF_LAYOUT)) {
    if ('number' === typeof value) {
      root.push(`--mf-${name}: ${value}px;`);
    } else {
      root.push(`--mf-${name}: ${value.base}px;`);
      responsive.push(`--mf-${name}: ${value.md}px;`);
    }
  }

  root.push('', '// Motion and layers.');
  for (const [name, ms] of Object.entries(MF_MOTION.duration)) root.push(`--mf-duration-${name}: ${ms}ms;`);
  for (const [name, value] of Object.entries(MF_MOTION.ease)) root.push(`--mf-ease-${name}: ${value};`);
  for (const [name, value] of Object.entries(MF_Z)) root.push(`--mf-z-${name}: ${value};`);

  const reduced = Object.keys(MF_MOTION.duration).map((name) => `--mf-duration-${name}: 0ms;`);
  const lines = [
    '// Generated by scripts/tokens-build.mjs from src/theme/tokens.ts. Do not edit: run `npm run tokens:build`.',
    '',
    ...block(':root', root),
    '',
    ...block(`@media (min-width: ${MF_BREAKPOINT_MD}px)`, block(':root', responsive)),
    '',
    ...block('@media (prefers-reduced-motion: reduce)', block(':root', reduced)),
    '',
    '// Dark theme door (DS-05): a future .v-theme--MoreFotoDarkTheme block redefines only --mf-color-* and tones.',
    ''
  ];
  return lines.join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(TOKENS_SCSS, render());
  console.log('Written ' + fileURLToPath(TOKENS_SCSS));
}
