// Generated by deploy/prepare-gallery.cjs. Source mapping: docs/frontend/gallery-selection.json.
import type { GalleryChild } from '../types.js';
export const galleryChildren: Record<string, GalleryChild[]> = {
  'sun-stars': [
    {
      code: 'A001',
      photos: [
        {
          id: 'sun-stars-A001-1',
          code: 'A001-01',
          thumbSrc: '/demo/gallery-v1/sun-stars/0f21215dfee629dee643-thumb.webp',
          previewSrc: '/demo/gallery-v1/sun-stars/0f21215dfee629dee643-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'sun-stars-A001-2',
          code: 'A001-02',
          thumbSrc: '/demo/gallery-v1/sun-stars/3d60f460cd8c1dedc63a-thumb.webp',
          previewSrc: '/demo/gallery-v1/sun-stars/3d60f460cd8c1dedc63a-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'sun-stars-A001-3',
          code: 'A001-03',
          thumbSrc: '/demo/gallery-v1/sun-stars/06fe2cf470976d563d32-thumb.webp',
          previewSrc: '/demo/gallery-v1/sun-stars/06fe2cf470976d563d32-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'sun-stars-A001-4',
          code: 'A001-04',
          thumbSrc: '/demo/gallery-v1/sun-stars/c83daf13a3fe0559bc33-thumb.webp',
          previewSrc: '/demo/gallery-v1/sun-stars/c83daf13a3fe0559bc33-preview.webp',
          width: 1200,
          height: 1800
        }
      ]
    },
    {
      code: 'A002',
      photos: [
        {
          id: 'sun-stars-A002-1',
          code: 'A002-01',
          thumbSrc: '/demo/gallery-v1/sun-stars/757798500b251e123870-thumb.webp',
          previewSrc: '/demo/gallery-v1/sun-stars/757798500b251e123870-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'sun-stars-A002-2',
          code: 'A002-02',
          thumbSrc: '/demo/gallery-v1/sun-stars/5eec67e4249393c5ecf1-thumb.webp',
          previewSrc: '/demo/gallery-v1/sun-stars/5eec67e4249393c5ecf1-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'sun-stars-A002-3',
          code: 'A002-03',
          thumbSrc: '/demo/gallery-v1/sun-stars/9c89928a665ee8cd5f30-thumb.webp',
          previewSrc: '/demo/gallery-v1/sun-stars/9c89928a665ee8cd5f30-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'sun-stars-A002-4',
          code: 'A002-04',
          thumbSrc: '/demo/gallery-v1/sun-stars/bf51ef8b2f92c315179a-thumb.webp',
          previewSrc: '/demo/gallery-v1/sun-stars/bf51ef8b2f92c315179a-preview.webp',
          width: 1200,
          height: 1800
        }
      ]
    },
    {
      code: 'A003',
      photos: [
        {
          id: 'sun-stars-A003-1',
          code: 'A003-01',
          thumbSrc: '/demo/gallery-v1/sun-stars/36f404fa7e3bfac17914-thumb.webp',
          previewSrc: '/demo/gallery-v1/sun-stars/36f404fa7e3bfac17914-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'sun-stars-A003-2',
          code: 'A003-02',
          thumbSrc: '/demo/gallery-v1/sun-stars/39c0ea239e6c4ac49f81-thumb.webp',
          previewSrc: '/demo/gallery-v1/sun-stars/39c0ea239e6c4ac49f81-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'sun-stars-A003-3',
          code: 'A003-03',
          thumbSrc: '/demo/gallery-v1/sun-stars/0c12fdfa7ec7e05b8f87-thumb.webp',
          previewSrc: '/demo/gallery-v1/sun-stars/0c12fdfa7ec7e05b8f87-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'sun-stars-A003-4',
          code: 'A003-04',
          thumbSrc: '/demo/gallery-v1/sun-stars/4e23db846eea515811ba-thumb.webp',
          previewSrc: '/demo/gallery-v1/sun-stars/4e23db846eea515811ba-preview.webp',
          width: 1200,
          height: 1800
        }
      ]
    },
    {
      code: 'A004',
      photos: [
        {
          id: 'sun-stars-A004-1',
          code: 'A004-01',
          thumbSrc: '/demo/gallery-v1/sun-stars/9c52ff5d3817eca4388d-thumb.webp',
          previewSrc: '/demo/gallery-v1/sun-stars/9c52ff5d3817eca4388d-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'sun-stars-A004-2',
          code: 'A004-02',
          thumbSrc: '/demo/gallery-v1/sun-stars/4f308c8dbbc8942da467-thumb.webp',
          previewSrc: '/demo/gallery-v1/sun-stars/4f308c8dbbc8942da467-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'sun-stars-A004-3',
          code: 'A004-03',
          thumbSrc: '/demo/gallery-v1/sun-stars/6576a734cca8b7dfef38-thumb.webp',
          previewSrc: '/demo/gallery-v1/sun-stars/6576a734cca8b7dfef38-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'sun-stars-A004-4',
          code: 'A004-04',
          thumbSrc: '/demo/gallery-v1/sun-stars/edd672846965dd04813c-thumb.webp',
          previewSrc: '/demo/gallery-v1/sun-stars/edd672846965dd04813c-preview.webp',
          width: 1200,
          height: 1800
        }
      ]
    }
  ],
  'school-1a': [
    {
      code: 'A001',
      photos: [
        {
          id: 'school-1a-A001-1',
          code: 'A001-01',
          thumbSrc: '/demo/gallery-v1/school-1a/39b073ade78a9bd8664d-thumb.webp',
          previewSrc: '/demo/gallery-v1/school-1a/39b073ade78a9bd8664d-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'school-1a-A001-2',
          code: 'A001-02',
          thumbSrc: '/demo/gallery-v1/school-1a/9d9157884862fc526724-thumb.webp',
          previewSrc: '/demo/gallery-v1/school-1a/9d9157884862fc526724-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'school-1a-A001-3',
          code: 'A001-03',
          thumbSrc: '/demo/gallery-v1/school-1a/e58498d72e48c955e230-thumb.webp',
          previewSrc: '/demo/gallery-v1/school-1a/e58498d72e48c955e230-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'school-1a-A001-4',
          code: 'A001-04',
          thumbSrc: '/demo/gallery-v1/school-1a/9387678d2a3262686dad-thumb.webp',
          previewSrc: '/demo/gallery-v1/school-1a/9387678d2a3262686dad-preview.webp',
          width: 1200,
          height: 1800
        }
      ]
    },
    {
      code: 'A002',
      photos: [
        {
          id: 'school-1a-A002-1',
          code: 'A002-01',
          thumbSrc: '/demo/gallery-v1/school-1a/d190b66c2615114c9179-thumb.webp',
          previewSrc: '/demo/gallery-v1/school-1a/d190b66c2615114c9179-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'school-1a-A002-2',
          code: 'A002-02',
          thumbSrc: '/demo/gallery-v1/school-1a/344ed5da612b08a77428-thumb.webp',
          previewSrc: '/demo/gallery-v1/school-1a/344ed5da612b08a77428-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'school-1a-A002-3',
          code: 'A002-03',
          thumbSrc: '/demo/gallery-v1/school-1a/0d7ae94b5acb4646dfb7-thumb.webp',
          previewSrc: '/demo/gallery-v1/school-1a/0d7ae94b5acb4646dfb7-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'school-1a-A002-4',
          code: 'A002-04',
          thumbSrc: '/demo/gallery-v1/school-1a/7b2c86b4a8f0011ae240-thumb.webp',
          previewSrc: '/demo/gallery-v1/school-1a/7b2c86b4a8f0011ae240-preview.webp',
          width: 1200,
          height: 1800
        }
      ]
    },
    {
      code: 'A003',
      photos: [
        {
          id: 'school-1a-A003-1',
          code: 'A003-01',
          thumbSrc: '/demo/gallery-v1/school-1a/c49b211beddb7a906ac9-thumb.webp',
          previewSrc: '/demo/gallery-v1/school-1a/c49b211beddb7a906ac9-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'school-1a-A003-2',
          code: 'A003-02',
          thumbSrc: '/demo/gallery-v1/school-1a/868938f35126a32a8dbf-thumb.webp',
          previewSrc: '/demo/gallery-v1/school-1a/868938f35126a32a8dbf-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'school-1a-A003-3',
          code: 'A003-03',
          thumbSrc: '/demo/gallery-v1/school-1a/ddb2ed770bdb6ea4b619-thumb.webp',
          previewSrc: '/demo/gallery-v1/school-1a/ddb2ed770bdb6ea4b619-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'school-1a-A003-4',
          code: 'A003-04',
          thumbSrc: '/demo/gallery-v1/school-1a/62c6d5d95e0170c6889f-thumb.webp',
          previewSrc: '/demo/gallery-v1/school-1a/62c6d5d95e0170c6889f-preview.webp',
          width: 1200,
          height: 1800
        }
      ]
    },
    {
      code: 'A004',
      photos: [
        {
          id: 'school-1a-A004-1',
          code: 'A004-01',
          thumbSrc: '/demo/gallery-v1/school-1a/6113e3e96a187ca36f43-thumb.webp',
          previewSrc: '/demo/gallery-v1/school-1a/6113e3e96a187ca36f43-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'school-1a-A004-2',
          code: 'A004-02',
          thumbSrc: '/demo/gallery-v1/school-1a/920c9e2695baf09212b4-thumb.webp',
          previewSrc: '/demo/gallery-v1/school-1a/920c9e2695baf09212b4-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'school-1a-A004-3',
          code: 'A004-03',
          thumbSrc: '/demo/gallery-v1/school-1a/8799d60ef57fcaa6362b-thumb.webp',
          previewSrc: '/demo/gallery-v1/school-1a/8799d60ef57fcaa6362b-preview.webp',
          width: 1200,
          height: 1800
        },
        {
          id: 'school-1a-A004-4',
          code: 'A004-04',
          thumbSrc: '/demo/gallery-v1/school-1a/1565158866acc63b47a6-thumb.webp',
          previewSrc: '/demo/gallery-v1/school-1a/1565158866acc63b47a6-preview.webp',
          width: 1200,
          height: 1800
        }
      ]
    }
  ]
};
