[Session]
session.save_handler = files
session.save_path = "/var/lib/php/sessions"
session.gc_maxlifetime = 86400
session.name = PHPSESSID
session.cookie_samesite = None
session.cookie_secure = 1
session.cookie_httponly = 1
; домен можно оставить по умолчанию (api.rebit-pro.ru),
; если нужно шарить между поддоменами – использовать .rebit-pro.ru
; session.cookie_domain = .rebit-pro.ru
