// Material Design Icons used by the cabinet: SVG paths from @mdi/js instead of the 400 KB icon font.
// Add an icon here before using its `mdi-*` name; tests/ui/icons.test.mjs checks that nothing is missing.
import {
  mdiAccount,
  mdiAccountCheckOutline,
  mdiAccountGroupOutline,
  mdiAccountOutline,
  mdiAccountPlusOutline,
  mdiAccountSearchOutline,
  mdiAlertCircleOutline,
  mdiArrowLeft,
  mdiArrowTopRight,
  mdiCalendarClockOutline,
  mdiCartOutline,
  mdiCheck,
  mdiCheckCircle,
  mdiCheckCircleOutline,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiCircle,
  mdiClockAlertOutline,
  mdiClockOutline,
  mdiClose,
  mdiCloudSyncOutline,
  mdiContentCopy,
  mdiDotsVertical,
  mdiDownload,
  mdiEye,
  mdiEyeOff,
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiFlaskOutline,
  mdiFolderOpenOutline,
  mdiFolderOutline,
  mdiGiftOutline,
  mdiHelpCircleOutline,
  mdiHome,
  mdiHomeCityOutline,
  mdiImageMultipleOutline,
  mdiImageOffOutline,
  mdiImageOutline,
  mdiInformationOutline,
  mdiLinkOff,
  mdiLinkVariant,
  mdiLock,
  mdiLogout,
  mdiMagnify,
  mdiMenuDown,
  mdiMessageTextOutline,
  mdiMinus,
  mdiPlus,
  mdiPrinterOutline,
  mdiReceiptTextOutline,
  mdiTagOutline,
  mdiTextBoxSearchOutline,
  mdiTimerSand,
  mdiTruckDeliveryOutline,
  mdiViewDashboardOutline
} from '@mdi/js';

export const MF_ICONS: Readonly<Record<string, string>> = {
  'mdi-account': mdiAccount,
  'mdi-account-check-outline': mdiAccountCheckOutline,
  'mdi-account-group-outline': mdiAccountGroupOutline,
  'mdi-account-outline': mdiAccountOutline,
  'mdi-account-plus-outline': mdiAccountPlusOutline,
  'mdi-account-search-outline': mdiAccountSearchOutline,
  'mdi-alert-circle-outline': mdiAlertCircleOutline,
  'mdi-arrow-left': mdiArrowLeft,
  'mdi-arrow-top-right': mdiArrowTopRight,
  'mdi-calendar-clock-outline': mdiCalendarClockOutline,
  'mdi-cart-outline': mdiCartOutline,
  'mdi-check': mdiCheck,
  'mdi-check-circle': mdiCheckCircle,
  'mdi-check-circle-outline': mdiCheckCircleOutline,
  'mdi-chevron-down': mdiChevronDown,
  'mdi-chevron-left': mdiChevronLeft,
  'mdi-chevron-right': mdiChevronRight,
  'mdi-chevron-up': mdiChevronUp,
  'mdi-circle': mdiCircle,
  'mdi-clock-alert-outline': mdiClockAlertOutline,
  'mdi-clock-outline': mdiClockOutline,
  'mdi-close': mdiClose,
  'mdi-cloud-sync-outline': mdiCloudSyncOutline,
  'mdi-content-copy': mdiContentCopy,
  'mdi-dots-vertical': mdiDotsVertical,
  'mdi-download': mdiDownload,
  'mdi-eye': mdiEye,
  'mdi-eye-off': mdiEyeOff,
  'mdi-eye-off-outline': mdiEyeOffOutline,
  'mdi-eye-outline': mdiEyeOutline,
  'mdi-flask-outline': mdiFlaskOutline,
  'mdi-folder-open-outline': mdiFolderOpenOutline,
  'mdi-folder-outline': mdiFolderOutline,
  'mdi-gift-outline': mdiGiftOutline,
  'mdi-help-circle-outline': mdiHelpCircleOutline,
  'mdi-home': mdiHome,
  'mdi-home-city-outline': mdiHomeCityOutline,
  'mdi-image-multiple-outline': mdiImageMultipleOutline,
  'mdi-image-off-outline': mdiImageOffOutline,
  'mdi-image-outline': mdiImageOutline,
  'mdi-information-outline': mdiInformationOutline,
  'mdi-link-off': mdiLinkOff,
  'mdi-link-variant': mdiLinkVariant,
  'mdi-lock': mdiLock,
  'mdi-logout': mdiLogout,
  'mdi-magnify': mdiMagnify,
  'mdi-menu-down': mdiMenuDown,
  'mdi-message-text-outline': mdiMessageTextOutline,
  'mdi-minus': mdiMinus,
  'mdi-plus': mdiPlus,
  'mdi-printer-outline': mdiPrinterOutline,
  'mdi-receipt-text-outline': mdiReceiptTextOutline,
  'mdi-tag-outline': mdiTagOutline,
  'mdi-text-box-search-outline': mdiTextBoxSearchOutline,
  'mdi-timer-sand': mdiTimerSand,
  'mdi-truck-delivery-outline': mdiTruckDeliveryOutline,
  'mdi-view-dashboard-outline': mdiViewDashboardOutline
};
